services:
  camoufox:
    build: .
    env_file:
      - ./.env
    volumes:
      - ./camoufox-py/config.yaml:/app/config.yaml
      - ./camoufox-py/cookies:/app/cookies
      - ./camoufox-py/logs:/app/logs
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
