services:
  camoufox:
    build: .
    environment:
      # 设置一个你最终Gemini服务的API密钥
      - ENV_VARIABLE: ${ENV_VARIABLE}
    volumes:
      - ./camoufox-py/config.yaml:/app/config.yaml
      - ./camoufox-py/cookies:/app/cookies
      - ./camoufox-py/logs:/app/logs
    restart: always
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
